services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      APP_KEY: base64:4c8otvNd4pLuSHEhyGaJTuilop2KugAQw3I9HRvcyag=
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/storage/database.sqlite
    volumes:
      - backend_storage:/var/www/html/storage

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  backend_storage:
